
import React from 'react';
import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    title: 'Zaathi',
    subtitle: 'Caregiver Companion',
    stats: {
      patients: 'Patients',
      medicines: 'Medicines',
      alerts: 'Active Alerts',
    },
    nav: {
      patients: 'Manage Patients',
      patientsDesc: 'Add and track patient info',
      medicines: 'Manage Medicines',
      medicinesDesc: 'Schedules and stock',
      alerts: 'Manage Alerts',
      alertsDesc: 'Set and track reminders',
      doctor: 'Doctor Notes',
      doctorDesc: 'Record clinical instructions',
      assistant: 'Zaathi AI',
      assistantDesc: 'Get AI voice help'
    },
    forms: {
      back: 'Back to Home',
      patientName: 'Patient Name',
      age: 'Age',
      condition: 'Medical Condition',
      addPatient: 'Add Patient',
      forPatient: 'For Patient',
      selectPatient: 'Select a patient',
      medicineName: 'Medicine Name',
      dosage: 'Dosage',
      schedule: 'Schedule Time',
      stock: 'Stock Quantity',
      addMedicine: 'Add Medicine',
      setReminder: 'Set Custom Alert',
      task: 'Task Description',
      time: 'Time',
      submitAlert: 'Create Alert',
      setMedAlert: 'Schedule Reminder',
      acknowledge: 'Acknowledge',
      quickAlert: 'Quick Alert',
      taken: 'Mark as Taken',
      snooze: 'Snooze 5m',
      remindLater: 'Remind at...',
      reschedule: 'Reschedule',
      doctorInstruction: 'Doctor\'s Instructions',
      saveNote: 'Save Note',
      viewSummary: 'Patient Summary',
      summarizing: 'Summarizing notes...',
      summaryTitle: 'Patient Care Reports',
      noNotes: 'No clinical notes recorded yet.',
      speak: 'Speak',
      stop: 'Stop',
      trySaying: 'Try saying:',
      examplePhrase: '"Set a reminder for John to check BP at 4 PM"',
      assistantTitle: 'Zaathi AI Assistant',
      printReport: 'Print Report',
      patientProfile: 'Patient Profile',
      doctorAdvice: 'Doctor\'s Advice & Notes',
      medSchedule: 'Current Medication Schedule',
      medicine: 'Medicine',
      generatedOn: 'Generated on'
    },
    voice: {
      guide: 'Voice Guide',
      speaking: 'Speaking...',
    },
    alerts: {
      critical: 'Critical Low Stock',
      upcoming: 'Upcoming Dose',
      reminder: 'Patient Alert',
      empty: 'No active alerts or reminders.'
    }
  },
  ml: {
    title: 'സാഥി',
    subtitle: 'കെയർഗിവർ സഹായി',
    stats: {
      patients: 'രോഗികൾ',
      medicines: 'മരുന്നുകൾ',
      alerts: 'അറിയിപ്പുകൾ',
    },
    nav: {
      patients: 'രോഗികളെ നോക്കുക',
      patientsDesc: 'വിവരങ്ങൾ ചേർക്കുക',
      medicines: 'മരുന്നുകൾ നോക്കുക',
      medicinesDesc: 'മരുന്ന് ക്രമീകരിക്കുക',
      alerts: 'അലർട്ടുകൾ നോക്കുക',
      alertsDesc: 'അലർട്ടുകൾ വെക്കുക',
      doctor: 'ഡോക്ടർ കുറിപ്പുകൾ',
      doctorDesc: 'നിർദ്ദേശങ്ങൾ രേഖപ്പെടുത്തുക',
      assistant: 'സാഥി സഹായി',
      assistantDesc: 'ശബ്ദ സഹായം'
    },
    forms: {
      back: 'തിരികെ',
      patientName: 'രോഗിയുടെ പേര്',
      age: 'പ്രായം',
      condition: 'അസുഖം',
      addPatient: 'രോഗിയെ ചേർക്കുക',
      forPatient: 'രോഗി',
      selectPatient: 'തിരഞ്ഞെടുക്കുക',
      medicineName: 'മരുന്നിന്റെ പേര്',
      dosage: 'അളവ്',
      schedule: 'സമയം',
      stock: 'സ്റ്റോക്ക്',
      addMedicine: 'മരുന്ന് ചേർക്കുക',
      setReminder: 'പുതിയ അലർട്ട്',
      task: 'എന്ത് ചെയ്യണം?',
      time: 'സമയം',
      submitAlert: 'അലർട്ട് വെക്കുക',
      setMedAlert: 'ഓർമ്മപ്പെടുത്തൽ',
      acknowledge: 'മനസ്സിലായി',
      quickAlert: 'അലർട്ട് വെക്കുക',
      taken: 'കഴിച്ചു',
      snooze: 'അഞ്ച് മിനിറ്റ് കഴിഞ്ഞ്',
      remindLater: 'മറ്റൊരു സമയം',
      reschedule: 'സമയം മാറ്റുക',
      doctorInstruction: 'ഡോക്ടറുടെ നിർദ്ദേശങ്ങൾ',
      saveNote: 'സേവ് ചെയ്യുക',
      viewSummary: 'സമ്മറി കാണുക',
      summarizing: 'സമ്മറി തയ്യാറാക്കുന്നു...',
      summaryTitle: 'പേഷ്യന്റ് കെയർ റിപ്പോർട്ട്',
      noNotes: 'കുറിപ്പുകൾ ഒന്നും ലഭ്യമല്ല.',
      speak: 'സംസാരിക്കൂ',
      stop: 'നിർത്തുക',
      trySaying: 'ഇന്നു പറയൂ:',
      examplePhrase: '"രാഹുലിന് 4 മണിക്ക് പനി നോക്കാൻ റിമൈൻഡർ വെക്കുക"',
      assistantTitle: 'സാഥി അസിസ്റ്റന്റ്',
      printReport: 'റിപ്പോർട്ട് പ്രിന്റ് ചെയ്യുക',
      patientProfile: 'രോഗിയുടെ പ്രൊഫൈൽ',
      doctorAdvice: 'ഡോക്ടറുടെ നിർദ്ദേശങ്ങൾ',
      medSchedule: 'മരുന്ന് സമയം',
      medicine: 'മരുന്ന്',
      generatedOn: 'തയ്യാറാക്കിയത്'
    },
    voice: {
      guide: 'ശബ്ദ സഹായി',
      speaking: 'പറയുന്നു...',
    },
    alerts: {
      critical: 'സ്റ്റോക്ക് തീരാറായി',
      upcoming: 'മരുന്ന് സമയം',
      reminder: 'ഓർമ്മപ്പെടുത്തൽ',
      empty: 'അറിയിപ്പുകൾ ഒന്നുമില്ല.'
    }
  },
  hi: { 
    title: 'साथी', 
    subtitle: 'देखभालकर्ता साथी', 
    stats: { 
      patients: 'मरीज़', 
      medicines: 'दवाइयाँ', 
      alerts: 'सक्रिय अलर्ट' 
    }, 
    nav: { 
      patients: 'मरीज़ों का प्रबंधन', 
      patientsDesc: 'मरीज़ की जानकारी जोड़ें और ट्रैक करें',
      medicines: 'दवा प्रबंधन', 
      medicinesDesc: 'शेड्यूल और स्टॉक',
      alerts: 'अलर्ट प्रबंधन', 
      alertsDesc: 'रिमाइंडर सेट करें और ट्रैक करें',
      doctor: 'डॉक्टर नोट्स', 
      doctorDesc: 'क्लिनिकल निर्देश रिकॉर्ड करें',
      assistant: 'साथी AI',
      assistantDesc: 'एआई वॉयस सहायता प्राप्त करें'
    }, 
    forms: { 
      back: 'वापस', 
      patientName: 'मरीज़ का नाम',
      age: 'उम्र',
      condition: 'चिकित्सा स्थिति',
      addPatient: 'मरीज़ जोड़ें', 
      forPatient: 'मरीज़ के लिए',
      selectPatient: 'मरीज़ चुनें',
      medicineName: 'दवा का नाम',
      dosage: 'खुराक',
      schedule: 'समय',
      stock: 'स्टॉक की मात्रा',
      addMedicine: 'दवा जोड़ें', 
      setReminder: 'कस्टम अलर्ट सेट करें',
      task: 'कार्य विवरण',
      time: 'समय',
      submitAlert: 'अलर्ट बनाएं',
      setMedAlert: 'रिमाइंडर शेड्यूल करें',
      acknowledge: 'ठीक है', 
      taken: 'ले लिया', 
      snooze: '5 मिनट रोकें', 
      remindLater: 'बाद में याद दिलाएं', 
      reschedule: 'रीशेड्यूल',
      doctorInstruction: 'डॉक्टर के निर्देश',
      saveNote: 'नोट सुरक्षित करें',
      viewSummary: 'सारांश',
      summaryTitle: 'रोगी देखभाल रिपोर्ट',
      noNotes: 'अभी तक कोई क्लिनिकल नोट रिकॉर्ड नहीं किया गया है।',
      speak: 'बोलें',
      stop: 'रुकें',
      trySaying: 'ये कहकर देखें:',
      examplePhrase: '"राहुल के लिए शाम 4 बजे बीपी चेक करने का रिमाइंडर सेट करें"',
      assistantTitle: 'साथी AI सहायक',
      printReport: 'रिपोर्ट प्रिंट करें',
      patientProfile: 'रोगी प्रोफ़ाइल',
      doctorAdvice: 'डॉक्टर की सलाह',
      medSchedule: 'दवा अनुसूची',
      medicine: 'दवा',
      generatedOn: 'दिनांक'
    }, 
    voice: { 
      guide: 'वॉयस गाइड', 
      speaking: 'बोल रहे हैं...' 
    }, 
    alerts: { 
      critical: 'कम स्टॉक', 
      upcoming: 'खुराक', 
      reminder: 'रिमाइंडर', 
      empty: 'कोई अलर्ट नहीं' 
    } 
  },
  ta: { 
    title: 'சாதி', 
    subtitle: 'பராமரிப்பாளர் துணை', 
    stats: { 
      patients: 'நோயாளிகள்', 
      medicines: 'மருந்துகள்', 
      alerts: 'எச்சரிக்கைகள்' 
    }, 
    nav: { 
      patients: 'நோயாளிகள் நிர்வகித்தல்', 
      patientsDesc: 'நோயாளி தகவலைச் சேர்த்து கண்காணிக்கவும்',
      medicines: 'மருந்து நிர்வகித்தல்', 
      medicinesDesc: 'அட்டவணைகள் மற்றும் இருப்பு',
      alerts: 'எச்சரிக்கை நிர்வகித்தல்', 
      alertsDesc: 'நினைவூட்டல்களை அமைத்துக் கண்காணிக்கவும்',
      doctor: 'டாக்டர் குறிப்புகள்', 
      doctorDesc: 'மருத்துவ வழிமுறைகளைப் பதிவு செய்யவும்',
      assistant: 'சாதி AI',
      assistantDesc: 'AI குரல் உதவியைப் பெறுங்கள்'
    }, 
    forms: { 
      back: 'முகப்பு', 
      patientName: 'நோயாளி பெயர்',
      age: 'வயது',
      condition: 'மருத்துவ நிலை',
      addPatient: 'நோயாளியைச் சேர்', 
      forPatient: 'நோயாளிக்கு',
      selectPatient: 'நோயாளியைத் தேர்ந்தெடுக்கவும்',
      medicineName: 'மருந்து பெயர்',
      dosage: 'அளவு',
      schedule: 'நேரம்',
      stock: 'இருப்பு அளவு',
      addMedicine: 'மருந்தைச் சேர்', 
      setReminder: 'தனிப்பயன் எச்சரிக்கை',
      task: 'பணி விவரம்',
      time: 'நேரம்',
      submitAlert: 'எச்சரிக்கையை உருவாக்கு',
      setMedAlert: 'நினைவூட்டலைத் திட்டமிடு',
      acknowledge: 'சரி', 
      taken: 'எடுத்துக்கொள்ளப்பட்டது', 
      snooze: '5 நிமிடம் தாமதிக்கவும்', 
      remindLater: 'பிறகு நினைவூட்டு', 
      reschedule: 'மீண்டும் திட்டமிடு',
      doctorInstruction: 'மருத்துவரின் அறிவுறுத்தல்கள்',
      saveNote: 'குறிப்பைச் சேமி',
      viewSummary: 'சுருக்கம்',
      summaryTitle: 'நோயாளி பராமரிப்பு அறிக்கை',
      noNotes: 'மருத்துவ குறிப்புகள் எதுவும் இதுவரை பதிவு செய்யப்படவில்லை.',
      speak: 'பேசவும்',
      stop: 'நிறுத்தவும்',
      trySaying: 'இப்படிச் சொல்லுங்கள்:',
      examplePhrase: '"ராகுலுக்கு மாலை 4 மணிக்கு இரத்த அழுத்தத்தை சரிபார்க்க நினைவூட்டலை அமைக்கவும்"',
      assistantTitle: 'சாதி AI உதவியாளர்',
      printReport: 'அறிக்கை அச்சு',
      patientProfile: 'நோயாளி விவரம்',
      doctorAdvice: 'டாக்டர் ஆலோசனை',
      medSchedule: 'மருந்து அட்டவணை',
      medicine: 'மருந்து',
      generatedOn: 'உருவாக்கப்பட்டது'
    }, 
    voice: { 
      guide: 'குரல் வழிகாட்டி', 
      speaking: 'பேசுகிறது...' 
    }, 
    alerts: { 
      critical: 'குறைவு', 
      upcoming: 'அடுத்தது', 
      reminder: 'நினைவூட்டல்', 
      empty: 'இல்லை' 
    } 
  },
  kn: { 
    title: 'ಸಾಥಿ', 
    subtitle: 'ಆರೈಕೆದಾರ ಸಹಚರ', 
    stats: { 
      patients: 'ರೋಗಿಗಳು', 
      medicines: 'ಔಷಧಗಳು', 
      alerts: 'ಎಚ್ಚರಿಕೆಗಳು' 
    }, 
    nav: { 
      patients: 'ರೋಗಿಗಳ ನಿರ್ವಹಣೆ', 
      patientsDesc: 'ರೋಗಿಯ ಮಾಹಿತಿಯನ್ನು ಸೇರಿಸಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
      medicines: 'ಔಷಧ ನಿರ್ವಹಣೆ', 
      medicinesDesc: 'ವೇಳಾಪಟ್ಟಿಗಳು ಮತ್ತು ಸ್ಟಾಕ್',
      alerts: 'ಎಚ್ಚರಿಕೆ ನಿರ್ವಹಣೆ', 
      alertsDesc: 'ಜ್ಞಾಪನೆಗಳನ್ನು ಹೊಂದಿಸಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
      doctor: 'ಡಾಕ್ಟರ್ ಟಿಪ್ಪಣಿ', 
      doctorDesc: 'ವೈದ್ಯಕೀಯ ಸೂಚನೆಗಳನ್ನು ದಾಖಲಿಸಿ',
      assistant: 'ಸಾಥಿ AI',
      assistantDesc: 'AI ಧ್ವನಿ ಸಹಾಯ ಪಡೆಯಿರಿ'
    }, 
    forms: { 
      back: 'ಮುಖಪುಟ', 
      patientName: 'ರೋಗಿಯ ಹೆಸರು',
      age: 'ವಯಸ್ಸು',
      condition: 'ವೈದ್ಯಕೀಯ ಸ್ಥಿತಿ',
      addPatient: 'ರೋಗಿಯನ್ನು ಸೇರಿಸಿ', 
      forPatient: 'ರೋಗಿಗಾಗಿ',
      selectPatient: 'ರೋಗಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      medicineName: 'ಔಷಧದ ಹೆಸರು',
      dosage: 'ಡೋಸೇಜ್',
      schedule: 'ಸಮಯ',
      stock: 'ಸ್ಟಾಕ್ ಪ್ರಮಾಣ',
      addMedicine: 'ಔಷಧವನ್ನು ಸೇರಿಸಿ', 
      setReminder: 'ಕಸ್ಟಮ್ ಎಚ್ಚರಿಕೆ',
      task: 'ಕೆಲಸದ ವಿವರ',
      time: 'ಸಮಯ',
      submitAlert: 'ಎಚ್ಚರಿಕೆ ರಚಿಸಿ',
      setMedAlert: 'ಜ್ಞಾಪನೆಯನ್ನು ನಿಗದಿಪಡಿಸಿ',
      acknowledge: 'ಸರಿ', 
      taken: 'ತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ', 
      snooze: '5 ನಿಮಿಷ ವಿಳಂಬ', 
      remindLater: 'ನಂತರ ನೆನಪಿಸಿ', 
      reschedule: 'ಮರು ನಿಗದಿಪಡಿಸಿ',
      doctorInstruction: 'ವೈದ್ಯರ ಸೂಚನೆಗಳು',
      saveNote: 'ಟಿಪ್ಪಣಿ ಉಳಿಸಿ',
      viewSummary: 'ಸಾರಾಂಶ',
      summaryTitle: 'ರೋಗಿ ಆರೈಕೆ ವರದಿ',
      noNotes: 'ಇನ್ನೂ ಯಾವುದೇ ವೈದ್ಯಕೀಯ ಟಿಪ್ಪಣಿಗಳನ್ನು ದಾಖಲಿಸಲಾಗಿಲ್ಲ.',
      speak: 'ಮಾತನಾಡಿ',
      stop: 'ನಿಲ್ಲಿಸಿ',
      trySaying: 'ಹೀಗೆ ಹೇಳಿ:',
      examplePhrase: '"ರಾಹುಲ್ ಅವರಿಗೆ ಸಂಜೆ 4 ಗಂಟೆಗೆ ಬಿಪಿ ಪರೀಕ್ಷಿಸಲು ಜ್ಞಾಪನೆಯನ್ನು ಹೊಂದಿಸಿ"',
      assistantTitle: 'ಸಾಥಿ AI ಸಹಾಯಕ',
      printReport: 'ವರದಿ ಮುದ್ರಿಸಿ',
      patientProfile: 'ರೋಗಿ ಪ್ರೊಫೈಲ್',
      doctorAdvice: 'ಡಾಕ್ಟರ್ ಸಲಹೆ',
      medSchedule: 'ಔಷಧಿ ವೇಳಾಪಟ್ಟಿ',
      medicine: 'ಔಷಧಿ',
      generatedOn: 'ರಚಿಸಲಾಗಿದೆ'
    }, 
    voice: { 
      guide: 'ಧ್ವನಿ ಮಾರ್ಗದರ್ಶಿ', 
      speaking: 'ಮಾತನಾಡುತ್ತಿದೆ...' 
    }, 
    alerts: { 
      critical: 'ಕಡಿಮೆ', 
      upcoming: 'ಸಮಯ', 
      reminder: 'ಜ್ಞಾಪನೆ', 
      empty: 'ಯಾವುದೂ ಇಲ್ಲ' 
    } 
  }
};

export const VOICE_MESSAGES: Record<Language, any> = {
  en: {
    patients: 'Manage patients section. Add name, age and medical condition.',
    medicines: 'Manage medicines and stock section. Record schedules and quantities.',
    alerts: 'Manage and set reminders for medication or tasks.',
    doctor: 'Doctor notes section. Record instructions from clinical visits here.',
    assistant: 'I am Zaathi. I can help you manage your patients, medicines, and alerts via voice.',
    successPatient: 'Patient successfully added to the system.',
    successMedicine: 'Medicine schedule successfully recorded.',
    successReminder: 'Custom alert has been set.',
    successNote: 'Clinical note saved successfully.',
    lowStock: 'Attention: Medicine stock is running dangerously low.',
    doseDue: 'Attention: A scheduled medicine dose is due now.',
    alertTriggered: 'Reminder alert:',
    actionTaken: 'Task marked as completed. Stock has been updated.',
    actionSnoozed: 'Alert snoozed for five minutes.',
    actionRescheduled: 'Reminders successfully rescheduled.',
    reportReady: 'The patient summary is ready for your review.'
  },
  ml: {
    patients: 'രോഗികളെ ചേർക്കുക. പേര്, പ്രായം, അസുഖം എന്നിവ നൽകുക.',
    medicines: 'മരുന്നുകൾ ക്രമീകരിക്കുക. സമയം, സ്റ്റോക്ക് എന്നിവ രേഖപ്പെടുത്താം.',
    alerts: 'മുന്നറിയിപ്പുകൾ ക്രമീകരിക്കുക.',
    doctor: 'ഡോക്ടറുടെ നിർദ്ദേശങ്ങൾ ഇവിടെ രേഖപ്പെടുത്താം.',
    assistant: 'ഞാൻ സാഥി. രോഗികളെ ചേർക്കാനും മരുന്നുകൾ ക്രമീകരിക്കാനും അലർട്ടുകൾ വെക്കാനും ഞാൻ സഹായിക്കാം.',
    successPatient: 'രോഗിയെ വിജയകരമായി ചേർത്തു.',
    successMedicine: 'മരുന്ന് വിവരങ്ങൾ രേഖപ്പെടുത്തി.',
    successReminder: 'അലർട്ട് വെച്ചിട്ടുണ്ട്.',
    successNote: 'കുറിപ്പ് വിജയകരമായി രേഖപ്പെടുത്തി.',
    lowStock: 'ശ്രദ്ധിക്കുക: മരുന്നിന്റെ സ്റ്റോക്ക് തീരാറായിരിക്കുന്നു.',
    doseDue: 'ശ്രദ്ധിക്കുക: മരുന്ന് കഴിക്കാനുള്ള സമയം ആയിരിക്കുന്നു.',
    alertTriggered: 'ഓർമ്മപ്പെടുത്തൽ:',
    actionTaken: 'രേഖപ്പെടുത്തി, സ്റ്റോക്ക് മാറ്റിയിട്ടുണ്ട്.',
    actionSnoozed: 'അഞ്ച് മിനിറ്റ് കഴിഞ്ഞ് ഓർമ്മിപ്പിക്കാം.',
    actionRescheduled: 'സമയം മാറ്റിയിട്ടുണ്ട്.',
    reportReady: 'സമ്മറി തയ്യാറായിട്ടുണ്ട്.'
  },
  hi: { 
    patients: 'मरीज़ प्रबंधन अनुभाग। मरीज़ का नाम, उम्र और चिकित्सा स्थिति जोड़ें।', 
    medicines: 'दवा और स्टॉक प्रबंधन। दवा का समय और मात्रा यहाँ दर्ज करें।', 
    alerts: 'दवा या अन्य कार्यों के लिए रिमाइंडर और अलर्ट यहाँ सेट करें।', 
    doctor: 'डॉक्टर नोट्स अनुभाग। डॉक्टर के निर्देशों को यहाँ सुरक्षित रखें।',
    assistant: 'मैं साथी हूँ। मैं आवाज़ के ज़रिए मरीज़ों, दवाओं और अलर्ट को प्रबंधित करने में आपकी मदद कर सकता हूँ।', 
    successPatient: 'मरीज़ को सफलतापूर्वक जोड़ दिया गया है।', 
    successMedicine: 'दवा का समय निर्धारित कर दिया गया है।', 
    successReminder: 'आपका अलर्ट सेट कर दिया गया है।', 
    successNote: 'डॉक्टर का निर्देश सुरक्षित कर लिया गया है।',
    lowStock: 'सावधान: दवा का स्टॉक बहुत कम हो गया है।', 
    doseDue: 'सावधान: दवा लेने का समय हो गया है।', 
    alertTriggered: 'रिमाइंडर अलर्ट:', 
    actionTaken: 'कार्य पूरा हो गया है। स्टॉक अपडेट कर दिया गया है।', 
    actionSnoozed: 'अलर्ट को पांच मिनट के लिए रोक दिया गया है।', 
    actionRescheduled: 'रिमाइंडर का समय बदल दिया गया है।', 
    reportReady: 'मरीज़ का सारांश तैयार है।'
  },
  ta: { 
    patients: 'நோயாளி மேலாண்மை பகுதி. பெயர், வயது மற்றும் மருத்துவ நிலையைச் சேர்க்கவும்.', 
    medicines: 'மருந்து மற்றும் இருப்பு மேலாண்மை. அட்டவணைகள் மற்றும் அளவுகளை இங்கே பதிவு செய்யவும்.', 
    alerts: 'மருந்து அல்லது பணிகளுக்கான நினைவூட்டல்களை இங்கே அமைக்கவும்.', 
    doctor: 'டாக்டர் குறிப்புகள் பகுதி. மருத்துவ ஆலோசனைகளை இங்கே சேமிக்கவும்.',
    assistant: 'நான் சாதி. குரல் வழியாக நோயாளிகள், மருந்துகள் மற்றும் எச்சரிக்கைகளை நிர்வகிக்க நான் உங்களுக்கு உதவுவேன்.', 
    successPatient: 'நோயாளி வெற்றிகரமாகச் சேர்க்கப்பட்டார்.', 
    successMedicine: 'மருந்து அட்டவணை பதிவு செய்யப்பட்டது.', 
    successReminder: 'எச்சரிக்கை வெற்றிகரமாக அமைக்கப்பட்டது.', 
    successNote: 'டாக்டர் குறிப்பு சேமிக்கப்பட்டது.',
    lowStock: 'கவனம்: மருந்தின் இருப்பு மிகக் குறைவாக உள்ளது.', 
    doseDue: 'கவனம்: மருந்து எடுத்துக்கொள்ள வேண்டிய நேரம் இது.', 
    alertTriggered: 'நினைவூட்டல் எச்சரிக்கை:', 
    actionTaken: 'பணி முடிக்கப்பட்டது. இருப்பு புதுப்பிக்கப்பட்டது.', 
    actionSnoozed: 'எச்சரிக்கை ஐந்து நிமிடங்களுக்குத் தள்ளி வைக்கப்பட்டது.', 
    actionRescheduled: 'நேரம் வெற்றிகரமாக மாற்றப்பட்டது.', 
    reportReady: 'நோயாளி பற்றிய சுருக்கம் தயாராக உள்ளது.'
  },
  kn: { 
    patients: 'ರೋಗಿಗಳ ನಿರ್ವಹಣಾ ವಿಭಾಗ. ಹೆಸರು, ವಯಸ್ಸು ಮತ್ತು ವೈದ್ಯಕೀಯ ಸ್ಥಿತಿಯನ್ನು ಸೇರಿಸಿ.', 
    medicines: 'ಔಷಧಿ ಮತ್ತು ಸ್ಟಾಕ್ ನಿರ್ವಹಣೆ. ವೇಳಾಪಟ್ಟಿ ಮತ್ತು ಪ್ರಮಾಣವನ್ನು ಇಲ್ಲಿ ದಾಖಲಿಸಿ.', 
    alerts: 'ಔಷಧಿ ಅಥವಾ ಕೆಲಸಗಳಿಗಾಗಿ ಜ್ಞಾಪನೆಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳನ್ನು ಇಲ್ಲಿ ಹೊಂದಿಸಿ.', 
    doctor: 'ಡಾಕ್ಟರ್ ಟಿಪ್ಪಣಿ ವಿಭಾಗ. ವೈದ್ಯರ ಸೂಚನೆಗಳನ್ನು ಇಲ್ಲಿ ದಾಖಲಿಸಿ.',
    assistant: 'ನಾನು ಸಾಥಿ. ಧ್ವನಿಯ ಮೂಲಕ ರೋಗಿಗಳು, ಔಷಧಿಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳನ್ನು ನಿರ್ವಹಿಸಲು ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ.', 
    successPatient: 'ರೋಗಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ.', 
    successMedicine: 'ಔಷಧಿಯ ವೇಳಾಪಟ್ಟಿಯನ್ನು ದಾಖಲಿಸಲಾಗಿದೆ.', 
    successReminder: 'ಎಚ್ಚರಿಕೆಯನ್ನು ಹೊಂದಿಸಲಾಗಿದೆ.', 
    successNote: 'ವೈದ್ಯರ ಟಿಪ್ಪಣಿಯನ್ನು ಉಳಿಸಲಾಗಿದೆ.',
    lowStock: 'ಗಮನಿಸಿ: ಔಷಧಿಯ ಸ್ಟಾಕ್ ತುಂಬಾ ಕಡಿಮೆಯಾಗಿದೆ.', 
    doseDue: 'ಗಮನಿಸಿ: ಔಷಧಿ ತೆಗೆದುಕೊಳ್ಳುವ ಸಮಯವಾಗಿದೆ.', 
    alertTriggered: 'ಜ್ಞಾಪನೆ ಎಚ್ಚರಿಕೆ:', 
    actionTaken: 'ಕೆಲಸ ಪೂರ್ಣಗೊಂಡಿದೆ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ. ಸ್ಟಾಕ್ ನವೀಕರಿಸಲಾಗಿದೆ.', 
    actionSnoozed: 'ಎಚ್ಚರಿಕೆಯನ್ನು ಐದು ನಿಮಿಷಗಳ ಕಾಲ ಮುಂದೂಡಲಾಗಿದೆ.', 
    actionRescheduled: 'ಜ್ಞಾಪನೆಯ ಸಮಯವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ.', 
    reportReady: 'ರೋಗಿಯ ಸಾರಾಂಶ ಸಿದ್ಧವಾಗಿದೆ.'
  }
};
